use_frameworks!

platform :ios, '13.0'

target 'HuracanDownloader_Example' do
  pod 'HuracanDownloader', :path => '../'

  target 'HuracanDownloader_Tests' do
    inherit! :search_paths

    
  end
end
